# Generated by Django 2.2 on 2019-04-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='heritage_link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ebay_link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pmg_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
