# Generated by Django 2.2.1 on 2019-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20190424_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.ImageField(upload_to='uploads\\detections')),
                ('back', models.ImageField(upload_to='uploads\\detections')),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='back',
            field=models.ImageField(upload_to='uploads\\bills'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='front',
            field=models.ImageField(upload_to='uploads\\bills'),
        ),
    ]
