# Generated by Django 2.2.1 on 2019-05-26 09:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20190522_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='result',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='detection',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
