# Generated by Django 2.2.1 on 2019-05-29 06:33

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20190526_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='back',
            field=models.ImageField(blank=True, upload_to='uploads\\bills'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='features',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='bill',
            name='front',
            field=models.ImageField(blank=True, upload_to='uploads\\bills'),
        ),
    ]
