# Generated by Django 2.2 on 2019-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('catalog', models.CharField(max_length=30)),
                ('front', models.ImageField(upload_to='')),
                ('back', models.ImageField(upload_to='')),
                ('pmg_link', models.CharField(max_length=256)),
                ('ebay_link', models.CharField(max_length=256)),
            ],
        ),
    ]
